/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package udpchatmulti;
import java.io.*;
import java.net.*;
import javax.swing.*;
/**
 *
 * @author Admin
 */
public class frmChat extends javax.swing.JFrame implements Runnable{
    private InetAddress group;//dia chi may muon chat
    private int port; //port >1024
    private String nick;
    private Thread mythread;// de xu ly cac package den
    private MulticastSocket socket;//truyn du lieu tu may truyen ra ben ngoai
    private DatagramPacket truyen, nhan; //truyen du lieu ra ben ngoai, nhan du lieu tu ben ngoai

    /**
     * Creates new form frmChat
     */
    public frmChat() {
        initComponents();
        txtgroup.setText("239.0.0.36");
        txtPort.setText("1234");
        txtPort.enable(false);
        txtgroup.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtgroup = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnick = new javax.swing.JTextField();
        btnketnoi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtnoidung = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtchat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhap dia chi Multicast");

        jLabel2.setText("Port");

        jLabel3.setText("Nick");

        btnketnoi.setText("Ket noi");
        btnketnoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketnoiActionPerformed(evt);
            }
        });

        jButton2.setText("Dong");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        txtchat.setColumns(20);
        txtchat.setRows(5);
        jScrollPane1.setViewportView(txtchat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(btnketnoi)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtgroup)
                            .addComponent(txtPort)
                            .addComponent(txtnick, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnoidung)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnsend)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btnketnoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(txtnoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnsend)
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnketnoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketnoiActionPerformed
        // TODO add your handling code here:
        if(btnketnoi.getText().equals("Connect")){ 

            //Khi nhấn nút kết nối 

            btnketnoi.setText("Disconnect"); 

            //chuyển nút kết nối thành nút ngắt kết nối 

            txtchat.setEnabled(true); 

            txtnoidung.setEnabled(true); 

            btnsend.setEnabled(true); 

            txtgroup.setEnabled(false); 

            txtPort.setEnabled(false); 

            txtnick.setEnabled(false); 

            try{ 

            group= InetAddress.getByName(txtgroup.getText()); 

            if(group.isMulticastAddress()){ 

                //Kiểm tra xem địa chỉ nhóm có phải địa chỉ multicast hay không 

                nick=txtnick.getText();                

                port=Integer.parseInt(txtPort.getText()); 

                if(mythread==null){ 

     //Tạo ra và thiết lập ban đầu cho các đối tượng mạng 

                    socket=new MulticastSocket(port); 

                    socket.setTimeToLive(1); 

     //Thiết lập đường đi cho gói tin 

                    socket.joinGroup(group); 

     //Đăng ký với router là chương trình máy mình đăng ký vào nhóm group 

                    truyen=new DatagramPacket(new byte[1],1,group,port); 

                    nhan=new DatagramPacket(new byte[65507],65507); 

                    //Tạo ra thread xử lý dữ liệu truyền đến 

                    mythread=new Thread(this); 

                    mythread.start(); 

     //Bắt đầu nhận dữ liệu - Lúc này hàm run sẽ dược gọi để thực thi 

                } 

            }else 

             JOptionPane.showMessageDialog(null, "Địa chỉ nhập sai rồi!!"); 

            }catch(Exception e){ 

            JOptionPane.showMessageDialog(null,e); 

            } 

        }else{ 

      //Sự kiện nhấn nút ngắt kết nối 

            txtchat.setEnabled(false); 

            txtnoidung.setEnabled(false); 

            btnsend.setEnabled(false); 

            txtgroup.setEnabled(true); 

            txtPort.setEnabled(true); 

            txtnick.setEnabled(true); 

            btnketnoi.setText("Connect"); 

           //chuyển nút ngắt kết nối thành nút kết nối 

            if(mythread!=null){ 

            mythread.interrupt(); 

 //dừng việc nhận dữ liệu 

            mythread=null; 

            try{ 

                socket.leaveGroup(group);//Ra khỏi group 

            }catch(IOException e){} 

            socket.close(); 

            } 

        } 
    }//GEN-LAST:event_btnketnoiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        try{
            byte[] utf = (nick + ": " + txtnoidung.getText()).getBytes("UTF8");//chuyen data thanh byte[]
            truyen.setData(utf);//gan data cho datagramPacket
            truyen.setLength(utf.length);
            socket.send(truyen);//bat dau truyen du lieu
            txtnoidung.setText("");            
            
        }
        catch(IOException e){
            if(mythread != null){
                txtchat.append(e + "\n");
                txtnoidung.setVisible(false);
                this.validate();
                
                if(mythread != Thread.currentThread())
                    mythread.interrupt();
                mythread = null;
                
                try{
                    socket.leaveGroup(group);
                }
                catch(IOException ignored){
                    socket.close();
                }
            }
        }
        
    }//GEN-LAST:event_btnsendActionPerformed
 private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        if(mythread != null){
            mythread.interrupt();
            mythread = null;

            try{
                socket.leaveGroup(group);
            }
            catch(IOException e){
                socket.close();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnketnoi;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextArea txtchat;
    private javax.swing.JTextField txtgroup;
    private javax.swing.JTextField txtnick;
    private javax.swing.JTextField txtnoidung;
    // End of variables declaration//GEN-END:variables

   // @Override
    public void run() {
       try{
            while(!Thread.interrupted()){
                nhan.setLength(nhan.getData().length);
                socket.receive(nhan);//nhan data
                String message = new String(nhan.getData(), 0, nhan.getLength(), "UTF8");
                txtchat.append(message + "\n");//show data
            }
        }
        catch(IOException e){
            if(mythread != null){
                txtchat.append(e +"\n");
                txtnoidung.setVisible(false);
                this.validate();
                if(mythread != Thread.currentThread())
                    mythread.interrupt();
                mythread = null;
                
                try{
                    socket.leaveGroup(group);
                }
                catch(IOException ignored){
                    socket.close();
                }
            }
        }
    }
}
